import { useMemo, useRef, useState } from 'react';
import { ArrowRight, CheckCircle, Headphones, Mic, PenLine, Play, RotateCcw, Square } from 'lucide-react';
import { post } from '../lib/api';
import { Button, Eyebrow, Panel } from '../components/ui';
import { speakAudioFirst } from '../lib/speech';

type Assessment={id:string;sections:Record<string,number>;items:Array<{id:string;term:string;definition_en:string;cefr:string}>};
type AssessmentResult={objective:{receptive:number;activeRecall:number;responses:number;averageResponseMs:number};evaluator:{writing:number;speaking:number;listening:number;grammar:number;naturalness:number};report:{workingCefr:string;confidence:string;receptiveVsActiveGap:number;focus:string[];topRecurringErrors:string[];disclaimer:string}};
type Section='receptive'|'active_recall'|'writing'|'speaking'|'listening';
const TOTAL=97;
const writingPrompts=['Write a concise message to a listing agent asking whether the space can be divided and whether taxes and CAM are included.','Compare two properties for a client. Recommend one, explain the trade-off, and state the next step.'];
const speakingPrompts=['Give a 60-second introduction covering your work, clients, and current priorities.','Explain a client’s requirements and decision criteria for two minutes.','Roleplay a call: open politely, clarify divisibility and CAM, handle a vague answer, confirm the next step, and close in 5–7 turns.'];
const listeningTasks=[{script:'The landlord is open to dividing the suite, but the quoted rent excludes taxes, insurance, and common area maintenance. Before we schedule a tour, please confirm your client’s preferred size and move-in date.',question:'What is excluded from rent? What must be confirmed before a tour? Summarize the message.'},{script:'Option A is more visible and available immediately, whereas Option B is less expensive and offers a longer improvement allowance. The decision depends on whether speed or long-term occupancy cost matters more.',question:'How do the options differ? What trade-off drives the decision? Give a one-sentence recommendation.'}];
function sectionFor(step:number):Section{return step<60?'receptive':step<90?'active_recall':step<92?'writing':step<95?'speaking':'listening';}

export function Assessment(){
  const [assessment,setAssessment]=useState<Assessment>();const [step,setStep]=useState(0);const [answer,setAnswer]=useState('');const [pronunciation,setPronunciation]=useState<{accuracyScore:number;fluencyScore:number;pronunciationScore:number}|null>(null);const [report,setReport]=useState<AssessmentResult>();const [replays,setReplays]=useState(0);const [speed,setSpeed]=useState(1);const [saving,setSaving]=useState(false);const [recording,setRecording]=useState(false);const [transcribing,setTranscribing]=useState(false);const [audioKey,setAudioKey]=useState('');const [audioError,setAudioError]=useState('');const started=useRef(Date.now());const mediaRecorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
  const start=()=>void post<Assessment>('/api/assessments').then((value)=>{setAssessment(value);started.current=Date.now();});
  const section=sectionFor(step);const item=assessment?.items[Math.min(step,89)];
  const prompt=useMemo(()=>{if(!assessment||!item)return'';if(section==='receptive'){const mode=step%3;return mode===0?`Explain “${item.term}” in this context: ${item.definition_en}`:mode===1?`Which meaning best matches “${item.term}”? Write the meaning in your own words.`:`Give a near-synonym or short contrast that proves you understand “${item.term}”.`;}if(section==='active_recall')return`Retrieve the natural English unit for this meaning or situation: ${item.definition_en}`;if(section==='writing')return writingPrompts[step-90];if(section==='speaking')return speakingPrompts[step-92];return listeningTasks[step-95].question;},[assessment,item,section,step]);
  const playListening=()=>{const task=listeningTasks[step-95];if(speakAudioFirst(task.script,{rate:speed}))setReplays((value)=>value+1);else setAudioError('Speech playback is unavailable in this browser.');};
  const toggleRecording=async()=>{if(recording){mediaRecorder.current?.stop();setRecording(false);return;}if(!assessment)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];setAudioError('');const active=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':undefined});mediaRecorder.current=active;active.ondataavailable=(event)=>chunks.current.push(event.data);active.onstop=()=>{stream.getTracks().forEach((track)=>track.stop());const form=new FormData();form.set('audio',new File(chunks.current,'assessment.webm',{type:active.mimeType||'audio/webm'}));form.set('referenceText',prompt);setTranscribing(true);void post<{audioKey:string;transcript:string;pronunciation?:{accuracyScore:number;fluencyScore:number;pronunciationScore:number}}>(`/api/assessments/${assessment.id}/transcribe`,form).then((value)=>{setAnswer(value.transcript);setAudioKey(value.audioKey);setPronunciation(value.pronunciation??null);}).catch((error:Error)=>setAudioError(error.message)).finally(()=>setTranscribing(false));};active.start();setRecording(true);}catch(error){setAudioError(error instanceof Error?error.message:'Microphone access failed.');}};
  const resetStep=()=>{setAnswer('');setAudioKey('');setPronunciation(null);setAudioError('');setReplays(0);started.current=Date.now();};
  const save=async(correct:boolean)=>{if(!assessment||!item)return;setSaving(true);try{await post(`/api/assessments/${assessment.id}/responses`,{itemId:section==='receptive'||section==='active_recall'?item.id:`${section}-${step}`,section,responseText:answer,audioKey:audioKey||undefined,pronunciation:pronunciation??undefined,responseMs:Date.now()-started.current,replayCount:section==='listening'?replays:0,hintLevel:0,correct});if(step===TOTAL-1){setReport(await post<AssessmentResult>(`/api/assessments/${assessment.id}/complete`));}else{setStep((value)=>value+1);resetStep();}}finally{setSaving(false);}};
  if(!assessment)return <div className="page"><div className="page-heading"><Eyebrow>WEEK 0 · BASELINE</Eyebrow><h1>Measure the gap<br/><em>between knowing and saying.</em></h1><p>This complete baseline includes 60 receptive items, 30 active-recall prompts, two writing tasks, three recorded speaking anchors, and two listening tasks. The result is a working estimate, never an official certificate.</p></div><div className="assessment-overview"><Panel><CheckCircle/><h3>Receptive vocabulary</h3><p>60 B1–C1 meaning, context, and contrast checks.</p></Panel><Panel><PenLine/><h3>Active & written output</h3><p>30 timed retrievals plus two real work messages.</p></Panel><Panel><Mic/><h3>Speaking anchors</h3><p>Recorded introduction, client requirements, and roleplay.</p></Panel><Panel><Headphones/><h3>Listening</h3><p>Two workplace clips with replay and speed tracked.</p></Panel></div><Button onClick={start}>Begin complete baseline <ArrowRight/></Button></div>;
  if(report)return <div className="page narrow"><div className="page-heading"><Eyebrow>WORKING ESTIMATE</Eyebrow><h1>{report.report.workingCefr}</h1><p>{report.report.disclaimer}</p></div><Panel className="assessment-report"><div className="metric-strip"><div className="metric"><span>Receptive</span><strong>{report.objective.receptive}%</strong></div><div className="metric"><span>Active recall</span><strong>{report.objective.activeRecall}%</strong></div><div className="metric"><span>Speaking</span><strong>{report.evaluator.speaking}/5</strong></div><div className="metric"><span>Responses</span><strong>{report.objective.responses}</strong></div></div><Eyebrow>12-WEEK FOCUS</Eyebrow><ol>{report.report.focus.map((focus)=><li key={focus}>{focus}</li>)}</ol><Eyebrow>TOP RECURRING ERRORS</Eyebrow><p>{report.report.topRecurringErrors.join(' · ')||'No stable error pattern identified.'}</p><p>Confidence: {report.report.confidence}. Average recorded response time: {(report.objective.averageResponseMs/1000).toFixed(1)} seconds.</p></Panel></div>;
  return <div className="page narrow"><div className="assessment-progress"><span style={{width:`${(step+1)/TOTAL*100}%`}}/></div><div className="assessment-kicker"><Eyebrow>{section.replace('_',' ')} · {step+1}/{TOTAL}</Eyebrow><button disabled={step===0} onClick={()=>{setStep((value)=>value-1);resetStep();}}>Back</button></div><Panel className="assessment-item"><p>{prompt}</p>{section==='speaking'&&<div className="listening-controls"><Button className={`ghost ${recording?'recording':''}`} disabled={transcribing} onClick={()=>void toggleRecording()}>{recording?<Square/>:<Mic/>}{recording?'Stop anchor':'Record speaking anchor'}</Button><small>{transcribing?'Transcribing securely…':audioKey?'Audio and transcript attached':'Speak for the requested duration; typing remains an accessibility fallback.'}</small></div>}{section==='listening'&&<div className="listening-controls"><Button className="ghost" onClick={playListening}>{replays?<RotateCcw/>:<Play/>}{replays?'Replay clip':'Play clip'}</Button><label>Speed <select value={speed} onChange={(event)=>setSpeed(Number(event.target.value))}><option value={0.8}>0.8×</option><option value={1}>1×</option><option value={1.15}>1.15×</option></select></label><small>{replays} play{replays===1?'':'s'} recorded</small></div>}<textarea autoFocus value={answer} onChange={(event)=>setAnswer(event.target.value)} placeholder={section==='speaking'?'Recorded speech is transcribed here; correct it only if STT misheard you…':section==='writing'?'Write your unaided response…':'Enter your answer before rating it…'}/>{audioError&&<small className="error-note">{audioError}</small>}<div><Button disabled={saving||transcribing} className="ghost" onClick={()=>void save(false)}>Needs work</Button><Button disabled={saving||transcribing||!answer.trim()} onClick={()=>void save(true)}>{step===TOTAL-1?'Complete & evaluate':'Save & continue'} <ArrowRight/></Button></div></Panel><small className="assessment-note">Answer without outside help. Audio follows the same 30-day retention rule as speaking practice; the assessment stores the transcript, timing, replay count, and evaluator evidence.</small></div>;
}
