import { useRef, useState } from 'react';
import { ArrowRight, CheckCircle, Headphones, Mic, PenLine, Play, RotateCcw, Square } from 'lucide-react';
import { post } from '../lib/api';
import { Button, Eyebrow, Panel } from '../components/ui';
import { speakAudioFirst } from '../lib/speech';

type Section='receptive'|'active_recall'|'writing'|'speaking'|'listening';
type AssessmentItem={id:string;unitId:string|null;section:Section;ordinal:number;prompt:string;options:string[];cefr:string|null;playbackText?:string};
type Assessment={id:string;sections:Record<string,number>;items:AssessmentItem[];total:number;currentTotal:number;scoring:string;adaptive:{machineSampleSize:number;rule:string}};
type SavedResponse={correct:boolean|null;score:number|null;nextItem:AssessmentItem|null};
type AssessmentResult={objective:{receptive:number;activeRecall:number;responses:number;averageResponseMs:number;machineScoredItems:number};evaluator:{writing:number;speaking:number;listening:number;grammar:number;naturalness:number};report:{workingCefr:string;confidence:string;receptiveVsActiveGap:number;focus:string[];topRecurringErrors:string[];disclaimer:string}};

export function Assessment(){
  const [assessment,setAssessment]=useState<Assessment>();const [step,setStep]=useState(0);const [answer,setAnswer]=useState('');const [report,setReport]=useState<AssessmentResult>();const [replays,setReplays]=useState(0);const [speed,setSpeed]=useState(1);const [saving,setSaving]=useState(false);const [recording,setRecording]=useState(false);const [transcribing,setTranscribing]=useState(false);const [audioKey,setAudioKey]=useState('');const [audioError,setAudioError]=useState('');const [pronunciation,setPronunciation]=useState<Record<string,unknown>|null>(null);const started=useRef(Date.now());const mediaRecorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
  const item=assessment?.items[step];const total=assessment?.total??0;
  const start=()=>void post<Assessment>('/api/assessments').then((value)=>{setAssessment(value);setStep(0);started.current=Date.now();});
  const resetStep=()=>{setAnswer('');setAudioKey('');setAudioError('');setPronunciation(null);setReplays(0);started.current=Date.now();};
  const playListening=()=>{if(!item?.playbackText)return;const played=speakAudioFirst(item.playbackText,{rate:speed});if(played)setReplays((value)=>value+1);else setAudioError('Speech playback is unavailable in this browser.');};
  const toggleRecording=async()=>{if(recording){mediaRecorder.current?.stop();setRecording(false);return;}if(!assessment||!item)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];setAudioError('');const active=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':undefined});mediaRecorder.current=active;active.ondataavailable=(event)=>chunks.current.push(event.data);active.onstop=()=>{stream.getTracks().forEach((track)=>track.stop());const form=new FormData();form.set('audio',new File(chunks.current,'assessment.webm',{type:active.mimeType||'audio/webm'}));form.set('referenceText',item.prompt);setTranscribing(true);void post<{audioKey:string;transcript:string;pronunciation?:Record<string,unknown>}>(`/api/assessments/${assessment.id}/transcribe`,form).then((value)=>{setAnswer(value.transcript);setAudioKey(value.audioKey);setPronunciation(value.pronunciation??null);}).catch((error:Error)=>setAudioError(error.message)).finally(()=>setTranscribing(false));};active.start();setRecording(true);}catch(error){setAudioError(error instanceof Error?error.message:'Microphone access failed.');}};
  const save=async()=>{if(!assessment||!item||!answer.trim())return;setSaving(true);try{const saved=await post<SavedResponse>(`/api/assessments/${assessment.id}/responses`,{itemId:item.id,section:item.section,responseText:answer,audioKey:audioKey||undefined,pronunciation:pronunciation??undefined,responseMs:Date.now()-started.current,replayCount:item.section==='listening'?replays:0,hintLevel:0});let items=assessment.items;if(saved.nextItem){items=[...assessment.items];items.splice(step+1,0,saved.nextItem);setAssessment({...assessment,items,currentTotal:items.length});}if(step===items.length-1)setReport(await post<AssessmentResult>(`/api/assessments/${assessment.id}/complete`));else{setStep((value)=>value+1);resetStep();}}finally{setSaving(false);}};
  if(!assessment)return <div className="page"><div className="page-heading"><Eyebrow>WEEK 0 · ADAPTIVE BASELINE</Eyebrow><h1>Measure the gap<br/><em>without self-scoring.</em></h1><p>Vocabulary is machine-scored with hidden answers and timed responses. The server routes the next B1/B2 item from recent verified accuracy while balancing recognition and active recall. Writing, speaking, and listening use fixed analytic rubrics. No word is shown twice.</p></div><div className="assessment-overview"><Panel><CheckCircle/><h3>Adaptive machine scoring</h3><p>Meaning choices use plausible distractors; active recall never displays the English answer.</p></Panel><Panel><PenLine/><h3>Written output</h3><p>A real work message scored against a fixed rubric.</p></Panel><Panel><Mic/><h3>Speaking anchors</h3><p>Recorded, transcribed, and evaluated rather than self-certified.</p></Panel><Panel><Headphones/><h3>Listening</h3><p>Replay count, speed, response, and timing are recorded.</p></Panel></div><Button onClick={start}>Begin adaptive baseline <ArrowRight/></Button></div>;
  if(report)return <div className="page narrow"><div className="page-heading"><Eyebrow>WORKING ESTIMATE</Eyebrow><h1>{report.report.workingCefr}</h1><p>{report.report.disclaimer}</p></div><Panel className="assessment-report"><div className="metric-strip"><div className="metric"><span>Receptive</span><strong>{report.objective.receptive}%</strong></div><div className="metric"><span>Active recall</span><strong>{report.objective.activeRecall}%</strong></div><div className="metric"><span>Speaking</span><strong>{report.evaluator.speaking}/5</strong></div><div className="metric"><span>Machine scored</span><strong>{report.objective.machineScoredItems}</strong></div></div><Eyebrow>12-WEEK FOCUS</Eyebrow><ol>{report.report.focus.map((focus)=><li key={focus}>{focus}</li>)}</ol><Eyebrow>TOP RECURRING ERRORS</Eyebrow><p>{report.report.topRecurringErrors.join(' · ')||'No stable error pattern identified.'}</p><p>Confidence: {report.report.confidence}. Average response time: {(report.objective.averageResponseMs/1000).toFixed(1)} seconds.</p></Panel></div>;
  if(!item)return <div className="page"/>;
  return <div className="page narrow"><div className="assessment-progress"><span style={{width:`${(step+1)/Math.max(total,1)*100}%`}}/></div><div className="assessment-kicker"><Eyebrow>{item.section.replace('_',' ')} · {step+1}/{total}</Eyebrow><button disabled={step===0} onClick={()=>{setStep((value)=>Math.max(0,value-1));resetStep();}}>Back</button></div><Panel className="assessment-item"><p>{item.prompt}</p>{item.section==='receptive'&&<div className="retry-list">{item.options.map((option)=><button className={`retry-item ${answer===option?'active':''}`} key={option} onClick={()=>setAnswer(option)}>{option}</button>)}</div>}{item.section==='speaking'&&<div className="listening-controls"><Button className={`ghost ${recording?'recording':''}`} disabled={transcribing} onClick={()=>void toggleRecording()}>{recording?<Square/>:<Mic/>}{recording?'Stop anchor':'Record speaking anchor'}</Button><small>{transcribing?'Transcribing securely…':audioKey?'Audio and transcript attached':'Recording is the primary evidence; typing remains an accessibility fallback.'}</small></div>}{item.section==='listening'&&<div className="listening-controls"><Button className="ghost" onClick={playListening}>{replays?<RotateCcw/>:<Play/>}{replays?'Replay clip':'Play clip'}</Button><label>Speed <select value={speed} onChange={(event)=>setSpeed(Number(event.target.value))}><option value={0.8}>0.8×</option><option value={1}>1×</option><option value={1.15}>1.15×</option></select></label><small>{replays} play{replays===1?'':'s'} recorded</small></div>}{item.section!=='receptive'&&<textarea autoFocus value={answer} onChange={(event)=>setAnswer(event.target.value)} placeholder={item.section==='speaking'?'Recorded speech is transcribed here…':item.section==='writing'?'Write your unaided response…':'Enter your answer before continuing…'}/>} {audioError&&<small className="error-note">{audioError}</small>}<Button disabled={saving||transcribing||!answer.trim()} onClick={()=>void save()}>{step===total-1?'Complete & score':'Save & continue'} <ArrowRight/></Button></Panel></div>;
}
