import { useEffect, useRef, useState } from 'react';
import { CloudOff, Mic, Send, ShieldCheck, Square } from 'lucide-react';
import { post } from '../lib/api';
import { queueCapture, queuedCaptures, removeQueuedCapture } from '../lib/offline';
import { Button, Eyebrow, Panel } from '../components/ui';

type Result={transcript?:string;redactionPreview:{findings:string[]};extracted:{naturalRewrite:string;units:Array<{term:string;definition:string}>}};
export function Capture(){
  const [text,setText]=useState('');const [context,setContext]=useState('');const [queued,setQueued]=useState(0);const [result,setResult]=useState<Result>();const [recording,setRecording]=useState(false);const [sendingAudio,setSendingAudio]=useState(false);const [recordingError,setRecordingError]=useState('');const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
  const refresh=()=>void queuedCaptures().then((items)=>setQueued(items.length));useEffect(refresh,[]);useEffect(()=>{const sync=async()=>{for(const item of await queuedCaptures()){try{await post('/api/captures',item);await removeQueuedCapture(item.id);}catch{return;}}refresh();};window.addEventListener('online',sync);if(navigator.onLine)void sync();return()=>window.removeEventListener('online',sync);},[]);
  const submit=async()=>{if(!navigator.onLine){await queueCapture({id:crypto.randomUUID(),captureType:'missed_phrase',text,context,createdAt:new Date().toISOString()});setText('');refresh();return;}setResult(await post<Result>('/api/captures',{captureType:'missed_phrase',text,context,redactAddresses:false}));};
  const toggleRecord=async()=>{if(recording){recorder.current?.stop();setRecording(false);return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];setRecordingError('');const active=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':undefined});recorder.current=active;active.ondataavailable=(event)=>chunks.current.push(event.data);active.onstop=()=>{stream.getTracks().forEach((track)=>track.stop());const form=new FormData();form.set('audio',new File(chunks.current,'capture.webm',{type:active.mimeType||'audio/webm'}));form.set('context',context);setSendingAudio(true);void post<Result>('/api/captures/audio',form).then((value)=>{setResult(value);setText(value.transcript??'');}).catch((error:Error)=>setRecordingError(error.message)).finally(()=>setSendingAudio(false));};active.start();setRecording(true);}catch(error){setRecordingError(error instanceof Error?error.message:'Microphone access failed.');}};
  return <div className="page narrow capture-page"><div className="page-heading"><Eyebrow>QUICK CAPTURE</Eyebrow><h1>Catch the gap<br/><em>before it disappears.</em></h1><p>Speak or paste what you heard, what you sent, or what you wanted to say. Redaction runs before AI extraction.</p></div><Panel><textarea autoFocus value={text} onChange={(event)=>setText(event.target.value)} placeholder="I wanted to say… / They said…"/><input value={context} onChange={(event)=>setContext(event.target.value)} placeholder="Optional context: phone call, showing, school…"/><div className="capture-foot"><span><ShieldCheck/>PII redaction preview enabled</span><div className="button-row"><Button className={`ghost ${recording?'recording':''}`} disabled={sendingAudio} onClick={()=>void toggleRecord()}>{recording?<Square/>:<Mic/>}{recording?'Stop':'Voice capture'}</Button><Button disabled={!text||sendingAudio} onClick={()=>void submit()}><Send/>Capture text</Button></div></div>{sendingAudio&&<div className="offline-note">Transcribing and extracting the useful language…</div>}{recordingError&&<small className="error-note">{recordingError}</small>}{queued>0&&<div className="offline-note"><CloudOff/>{queued} capture{queued>1?'s':''} waiting for a connection.</div>}</Panel>{result&&<Panel className="capture-result">{result.transcript&&<><Eyebrow>TRANSCRIPT</Eyebrow><p>{result.transcript}</p></>}<Eyebrow>NATURAL REWRITE</Eyebrow><h2>{result.extracted.naturalRewrite}</h2><Eyebrow>WORTH REVIEWING</Eyebrow>{result.extracted.units.map((unit)=><div className="captured-unit" key={unit.term}><strong>{unit.term}</strong><p>{unit.definition}</p></div>)}{result.redactionPreview.findings.length>0&&<small>Redacted: {result.redactionPreview.findings.join(', ')}</small>}</Panel>}</div>;
}
