import { useEffect, useRef, useState } from 'react';
import { CheckCircle2, Mic, RotateCcw, Square, Timer } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { api, post } from '../lib/api';
import { Button, Empty, Eyebrow, Panel } from '../components/ui';
import { SpeechButton } from '../components/SpeechButton';
import { speakAudioFirst } from '../lib/speech';

type Unit={id:string;term:string;definition_en:string;definition_zh:string;model_answer:string;adaptive_score:number};
type AnswerResult={correct:boolean;score:number;transcript:string;feedback:string};

export function Drill(){
  const [params]=useSearchParams();const navigate=useNavigate();const planItemId=params.get('planItemId');const [units,setUnits]=useState<Unit[]>([]);const [loaded,setLoaded]=useState(false);const [sessionId,setSessionId]=useState('');const [index,setIndex]=useState(0);const [seconds,setSeconds]=useState(8);const [show,setShow]=useState(false);const [response,setResponse]=useState('');const [correct,setCorrect]=useState(0);const [saving,setSaving]=useState(false);const [recording,setRecording]=useState(false);const [feedback,setFeedback]=useState('');const started=useRef(Date.now());const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
  useEffect(()=>{void Promise.all([api<{units:Unit[]}>('/api/drills/queue?limit=10'),post<{id:string}>('/api/drills/sessions',{planItemId:planItemId??undefined})]).then(([data,session])=>{setUnits(data.units);setSessionId(session.id);}).finally(()=>setLoaded(true));},[planItemId]);
  useEffect(()=>{if(show)return;const timer=setInterval(()=>setSeconds((value)=>value<=1?(setShow(true),0):value-1),1000);return()=>clearInterval(timer);},[index,show]);
  const total=units.length*3;const unit=units[Math.floor(index/3)];const variant=index%3+1;
  const prompt=unit?(variant===1?(unit.definition_zh||unit.definition_en):variant===2?`In a work call, use “${unit.term}” in a complete natural response.`:`Use “${unit.term}” in a different real-life sentence.`):'';
  const model=unit?(variant===1?unit.term:unit.model_answer):'';
  const advance=async()=>{const next=index+1;if(next>=total){await post(`/api/drills/sessions/${sessionId}/complete`,{});setIndex(next);if(planItemId)void navigate('/session');return;}setIndex(next);setSeconds(8);setShow(false);setResponse('');setFeedback('');started.current=Date.now();};
  const submit=async(body:string|FormData)=>{if(!unit)return;setSaving(true);try{const result=body instanceof FormData?await post<AnswerResult>(`/api/drills/sessions/${sessionId}/answers`,body):await post<AnswerResult>(`/api/drills/sessions/${sessionId}/answers`,{unitId:unit.id,prompt,response:body,responseMs:Date.now()-started.current,variant,planItemId:planItemId??undefined});setResponse(result.transcript);setFeedback(`${result.score}% · ${result.feedback}`);setShow(true);if(result.correct){setCorrect((value)=>value+1);setTimeout(()=>void advance(),650);}}finally{setSaving(false);}};
  const toggleRecord=async()=>{if(recording){recorder.current?.stop();setRecording(false);return;}if(!unit)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const active=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':undefined});recorder.current=active;active.ondataavailable=(event)=>chunks.current.push(event.data);active.onstop=()=>{stream.getTracks().forEach((track)=>track.stop());const form=new FormData();form.set('audio',new File(chunks.current,'drill.webm',{type:active.mimeType||'audio/webm'}));form.set('unitId',unit.id);form.set('prompt',prompt);form.set('responseMs',String(Date.now()-started.current));form.set('variant',String(variant));if(planItemId)form.set('planItemId',planItemId);void submit(form);};active.start();setRecording(true);}catch(error){setFeedback(error instanceof Error?error.message:'Microphone access failed.');}};
  if(loaded&&!units.length)return <div className="page narrow"><Empty title="Learn a target before drilling">The drill queue only uses introduced units, recent errors, today’s targets, and recall–production gaps. Unseen words are never treated as due practice.</Empty></div>;
  if(units.length&&index>=total)return <div className="page narrow"><Empty title="Automaticity sprint complete">The server verified {correct} of {total} productions and saved response time, transcript, and learning evidence.</Empty></div>;
  if(!unit)return <div className="page"/>;
  const reveal=()=>{setShow(true);speakAudioFirst(model);};
  return <div className="page narrow"><div className="page-heading"><Eyebrow>ADAPTIVE AUTOMATICITY · {index+1}/{total}</Eyebrow><h1>Eight seconds.<br/><em>Say it now.</em></h1><p>The server verifies the target expression and a complete response. A failed attempt stays here for an immediate re-say.</p></div><Panel className="drill-card"><div className="timer"><Timer/>{seconds}</div><Eyebrow>VARIATION {variant}/3</Eyebrow><p>{prompt}</p><div className="button-row"><Button className={`ghost ${recording?'recording':''}`} disabled={saving} onClick={()=>void toggleRecord()}>{recording?<Square/>:<Mic/>}{recording?'Stop & check':'Record answer'}</Button><small>Recorded answers are transcribed and verified.</small></div><textarea value={response} onChange={(event)=>setResponse(event.target.value)} placeholder="Or type exactly what you said…"/>{feedback&&<p className={feedback.startsWith('0%')||feedback.startsWith('20%')?'error-note':''}>{feedback}</p>}{show?<div className="drill-answer"><h2>{model}</h2><SpeechButton text={model} label="Replay model answer"/><div className="button-row"><Button disabled={saving||!response.trim()} onClick={()=>void submit(response)}>{feedback&&!feedback.includes('verified')?<RotateCcw/>:<CheckCircle2/>}{feedback?'Check re-say':'Check response'}</Button></div></div>:<Button onClick={reveal}>Reveal & hear model</Button>}</Panel></div>;
}
