import { useEffect, useRef, useState } from 'react';
import { Mic, Plus, Square } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { api, post } from '../lib/api';
import { useAsync } from '../hooks';
import { Button, Eyebrow, Metric, Panel } from '../components/ui';
import { SpeechButton } from '../components/SpeechButton';

type UnitData={unit:Record<string,unknown>;personalExamples:Array<{id:string;text:string}>};
export function Learn(){
  const {unitId}=useParams();const state=useAsync(()=>apiUnit(unitId),[unitId]);const [example,setExample]=useState('');const [recording,setRecording]=useState(false);const [recordedUrl,setRecordedUrl]=useState('');const [recordingError,setRecordingError]=useState('');const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
  useEffect(()=>()=>{if(recordedUrl)URL.revokeObjectURL(recordedUrl);},[recordedUrl]);
  if(!state.data)return <div className="page"/>;const u=state.data.unit;const list=(key:string)=>{try{return JSON.parse(String(u[key])) as Array<string|{text:string}>}catch{return[]}};
  const toggleRecord=async()=>{if(recording){recorder.current?.stop();setRecording(false);return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];setRecordingError('');const active=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':undefined});recorder.current=active;active.ondataavailable=(event)=>chunks.current.push(event.data);active.onstop=()=>{stream.getTracks().forEach((track)=>track.stop());if(recordedUrl)URL.revokeObjectURL(recordedUrl);setRecordedUrl(URL.createObjectURL(new Blob(chunks.current,{type:active.mimeType})));};active.start();setRecording(true);}catch(error){setRecordingError(error instanceof Error?error.message:'Microphone access failed.');}};
  return <div className="page learn-page"><div className="word-hero"><Eyebrow>{String(u.unit_type).toUpperCase()} · {String(u.cefr)} · {String(u.register)}</Eyebrow><h1>{String(u.term)}</h1><p className="ipa">{String(u.ipa??'American English')}</p><div className="word-actions"><SpeechButton text={String(u.term)} label="Hear pronunciation"/><Button className={`ghost ${recording?'recording':''}`} onClick={()=>void toggleRecord()}>{recording?<Square/>:<Mic/>}{recording?'Stop recording':'Record yourself'}</Button></div>{recordedUrl&&<div className="recording-playback"><audio controls src={recordedUrl}/><small>Compare your stress, rhythm, and final consonants with Hear pronunciation. This recording stays in this browser tab.</small></div>}{recordingError&&<small className="error-note">{recordingError}</small>}</div><div className="learn-grid"><Panel><Eyebrow>MEANING</Eyebrow><h2>{String(u.definition_en)}</h2><p className="zh">{String(u.definition_zh??'')}</p><Eyebrow>COLLOCATIONS</Eyebrow><div className="chips">{list('collocations_json').map((item)=><span key={String(item)}>{String(item)}</span>)}</div></Panel><Panel><Eyebrow>MASTERY PROFILE</Eyebrow><div className="metric-grid"><Metric label="Recognition" value={`${Math.round(Number(u.recognition_score))}%`}/><Metric label="Recall" value={`${Math.round(Number(u.recall_score))}%`}/><Metric label="Production" value={`${Math.round(Number(u.production_score))}%`}/><Metric label="Transfer" value={`${Math.round(Number(u.transfer_score))}%`}/></div></Panel><Panel className="wide"><Eyebrow>EXAMPLES IN CONTEXT</Eyebrow><ol className="examples">{list('examples_json').map((item)=>{const text=typeof item==='string'?item:item.text;return <li key={text}><span>{text}</span><SpeechButton text={text} label="Play example"/></li>})}</ol>{state.data.personalExamples.map((item)=><blockquote key={item.id}>{item.text}</blockquote>)}<div className="personal-example"><input value={example} onChange={(event)=>setExample(event.target.value)} placeholder="Add a sentence from your own work or life"/><Button disabled={!example} onClick={()=>void post(`/api/units/${unitId}/personal-example`,{text:example}).then(()=>{setExample('');return state.reload();})}><Plus/>Save</Button></div></Panel></div></div>;
}

function apiUnit(unitId:string|undefined){return api<UnitData>(`/api/units/${unitId??''}`);}
