import { useState } from 'react';
import { ArrowRight, Check, MessageCircle, Printer } from 'lucide-react';
import { Link } from 'react-router-dom';
import { post } from '../lib/api';
import { Button, Eyebrow, Panel } from '../components/ui';
import { SpeechButton } from '../components/SpeechButton';

type Prep={id:string;event:string;mustUse:Array<{id:string;term:string}>;recommendedOpening:string;likelyFollowUps:string[];possibleResponses:string[];cheatSheet:string[]};
type AfterAction={followUp:string|null;extracted:{naturalRewrite:string;units:Array<{term:string;definition:string}>}};
export function Prepare(){
  const [event,setEvent]=useState('Tomorrow I need to call the listing agent to confirm whether the space can be subdivided and ask about taxes and CAM.');const [prep,setPrep]=useState<Prep>();const [happened,setHappened]=useState('');const [missedPhrase,setMissedPhrase]=useState('');const [unfamiliarExpression,setUnfamiliarExpression]=useState('');const [createFollowUp,setCreateFollowUp]=useState(true);const [after,setAfter]=useState<AfterAction>();const [saving,setSaving]=useState(false);
  const create=()=>void post<Prep>('/api/event-prep',{event}).then(setPrep);
  const submitAfter=()=>{if(!prep)return;setSaving(true);void post<AfterAction>(`/api/event-prep/${prep.id}/after-action`,{happened,missedPhrase,unfamiliarExpression,createFollowUp}).then(setAfter).finally(()=>setSaving(false));};
  return <div className="page"><div className="page-heading"><Eyebrow>EVENT PREP</Eyebrow><h1>Practice tomorrow’s<br/><em>real conversation today.</em></h1></div><Panel className="prep-input"><label>What is going to happen?</label><textarea value={event} onChange={(eventChange)=>setEvent(eventChange.target.value)}/><Button onClick={create}>Build my preparation <ArrowRight/></Button></Panel>{prep&&<><div className="prep-sheet"><div className="sheet-head"><div><Eyebrow>PHONE CHEAT SHEET</Eyebrow><h2>{prep.event}</h2></div><button onClick={()=>window.print()}><Printer/>Print</button></div><div className="sheet-grid"><section><Eyebrow>OPEN WITH</Eyebrow><blockquote>{prep.recommendedOpening}</blockquote><SpeechButton text={prep.recommendedOpening} label="Hear opening"/><Eyebrow>FIVE MUST-USE UNITS</Eyebrow>{prep.mustUse.map((item)=><div className="check-line" key={item.id}><Check/>{item.term}<SpeechButton text={item.term} label="Listen"/></div>)}</section><section><Eyebrow>LIKELY FOLLOW-UPS</Eyebrow><ol>{prep.likelyFollowUps.map((item)=><li key={item}><span>{item}</span><SpeechButton text={item} label="Play"/></li>)}</ol><Eyebrow>EXPECT SOME FRICTION</Eyebrow><ul>{prep.possibleResponses.map((item)=><li key={item}><span>{item}</span><SpeechButton text={item} label="Play"/></li>)}</ul><Link className="button" to="/speak"><MessageCircle/>Run the voice simulation</Link></section></div></div><Panel className="after-action"><Eyebrow>AFTER ACTION REVIEW</Eyebrow><h2>Close the loop after the real event.</h2><label>What actually happened?<textarea value={happened} onChange={(change)=>setHappened(change.target.value)} placeholder="Outcome, next step, and what felt difficult…"/></label><div className="after-grid"><label>What could you not say?<textarea value={missedPhrase} onChange={(change)=>setMissedPhrase(change.target.value)}/></label><label>What unfamiliar expression did they use?<textarea value={unfamiliarExpression} onChange={(change)=>setUnfamiliarExpression(change.target.value)}/></label></div><label className="check-line"><input type="checkbox" checked={createFollowUp} onChange={(change)=>setCreateFollowUp(change.target.checked)}/>Create a concise follow-up message</label><Button disabled={!happened.trim()||saving} onClick={submitAfter}>{saving?'Analyzing…':'Save review & create learning units'}</Button>{after&&<div className="after-result"><Eyebrow>NATURAL RETELLING</Eyebrow><p>{after.extracted.naturalRewrite}</p><SpeechButton text={after.extracted.naturalRewrite} label="Hear natural retelling"/>{after.extracted.units.map((unit)=><div className="captured-unit" key={unit.term}><strong>{unit.term}</strong><p>{unit.definition}</p><SpeechButton text={unit.term} label="Hear phrase"/></div>)}{after.followUp&&<><Eyebrow>FOLLOW-UP DRAFT</Eyebrow><blockquote>{after.followUp}</blockquote><SpeechButton text={after.followUp} label="Hear follow-up"/></>}</div>}</Panel></>}</div>;
}
