import { useState } from 'react';
import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api, post } from '../lib/api';
import { useAsync } from '../hooks';
import { Button, Empty, Eyebrow, Metric, Panel } from '../components/ui';

type Summary={unitStatusFunnel:Array<{status:string;count:number}>;reviews:{reviews:number;activeRecallAccuracy:number|null};speaking:{speakingMinutes:number};transfer:{transferCount:number};errors:{recurrentErrors:number|null};workingEstimate:string};
type Timeseries={reviews:Array<{date:string;recallAccuracy:number;reviews:number}>;speaking:Array<{date:string;minutes:number}>};
type Weekly={id:string;week_start:string;week_end:string;narrative_json:string;created_at:string};
export function Progress(){
  const summary=useAsync(()=>api<Summary>('/api/progress/summary'),[]);const series=useAsync(()=>api<Timeseries>('/api/progress/timeseries'),[]);const reports=useAsync(()=>api<{reports:Weekly[]}>('/api/reports/weekly'),[]);const [reportStatus,setReportStatus]=useState('');const funnel=summary.data?.unitStatusFunnel??[];
  const generate=()=>{setReportStatus('Generating with objective metrics…');void post<{status:string}>('/api/reports/weekly/generate',{}).then((result)=>{setReportStatus(result.status==='complete'?'Current report is ready.':'Workflow started. Refresh shortly to open it.');return reports.reload();}).catch((error:Error)=>setReportStatus(error.message));};
  return <div className="page"><div className="page-heading split"><div><Eyebrow>PROGRESS · EVIDENCE, NOT HYPE</Eyebrow><h1>What became<br/><em>available in real use?</em></h1></div><div className="estimate"><span>WORKING ESTIMATE</span><strong>{summary.data?.workingEstimate??'—'}</strong><small>Not an official CEFR certification</small></div></div><div className="metric-strip"><Metric label="30-day recall" value={`${summary.data?.reviews.activeRecallAccuracy??0}%`} detail={`${summary.data?.reviews.reviews??0} reviews`}/><Metric label="Speaking output" value={`${summary.data?.speaking.speakingMinutes??0}m`} detail="last 30 days"/><Metric label="Real-world transfer" value={summary.data?.transfer.transferCount??0} detail="confirmed uses"/><Metric label="Recurring errors" value={summary.data?.errors.recurrentErrors??0} detail="tracked, not hidden"/></div><div className="progress-grid"><Panel className="chart"><Eyebrow>ACTIVE RECALL ACCURACY</Eyebrow><ResponsiveContainer width="100%" height={280}><AreaChart data={series.data?.reviews??[]}><defs><linearGradient id="recall" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#a7c636" stopOpacity={.5}/><stop offset="100%" stopColor="#a7c636" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date"/><YAxis domain={[0,100]}/><Tooltip/><Area type="monotone" dataKey="recallAccuracy" stroke="#6f8422" fill="url(#recall)" strokeWidth={3}/></AreaChart></ResponsiveContainer></Panel><Panel><Eyebrow>UNIT STATUS FUNNEL</Eyebrow><div className="funnel">{funnel.map((item)=>{const max=Math.max(...funnel.map((value)=>value.count),1);return <div key={item.status}><span>{item.status}</span><div><i style={{width:`${item.count/max*100}%`}}/></div><strong>{item.count}</strong></div>})}</div></Panel></div><Panel className="weekly-reports"><div className="panel-head"><div><Eyebrow>WEEKLY REPORTS</Eyebrow><h2>Objective change, interpreted carefully</h2></div><Button className="ghost" onClick={generate}>Generate current week</Button></div>{reportStatus&&<p>{reportStatus}</p>}{reports.data?.reports.length?reports.data.reports.slice(0,8).map((report)=><Link className="report-row" to={`/reports/${report.id}`} key={report.id}><div><strong>{report.week_start} → {report.week_end}</strong><small>Generated {new Date(report.created_at).toLocaleDateString()}</small></div><ArrowRight/></Link>):<Empty title="No weekly report yet">Generate one now or let the Sunday workflow create it automatically.</Empty>}</Panel></div>;
}
