import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Mic, Phone, Radio, Send, Square } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { api, post } from '../lib/api';
import { useAsync } from '../hooks';
import { Button, Empty, Eyebrow, Panel } from '../components/ui';
import { SpeechButton } from '../components/SpeechButton';
import { speakEnglish } from '../lib/speech';

type Scenario={id:string;title:string;domain:string;difficulty:string;ai_role:string;user_objective:string;target_units_json:string};
const modes=[['fluency','Fluency'],['drill','Drill & retry'],['monologue','Monologue'],['objection','Objection handling'],['phone','Phone call'],['small_talk','Small talk']] as const;
export function Speak(){const state=useAsync(()=>api<{scenarios:Scenario[]}>('/api/speaking/scenarios'),[]);const navigate=useNavigate();const [mode,setMode]=useState<(typeof modes)[number][0]>('fluency');const start=(scenario:Scenario)=>void post<{id:string}>('/api/speaking/sessions',{scenarioId:scenario.id,mode,title:scenario.title}).then((result)=>navigate(`/speak/${result.id}`));return <div className="page"><div className="page-heading split"><div><Eyebrow>SPEAKING COACH</Eyebrow><h1>Complete the task.<br/><em>Feedback comes after.</em></h1><p>Turn-based voice practice keeps the learning loop reliable: record, transcribe, respond, analyze, retry.</p></div><div className="mode-legend"><span><Radio/>Fluency mode</span><span><Mic/>Drill & retry</span><span><Phone/>Phone simulation</span></div></div><div className="task-tabs speaking-modes">{modes.map(([value,label])=><button className={mode===value?'active':''} onClick={()=>setMode(value)} key={value}>{label}</button>)}</div><div className="scenario-grid">{state.data?.scenarios.slice(0,12).map((scenario)=><Panel key={scenario.id}><div className="scenario-meta"><span>{scenario.domain.replace('_',' ')}</span><span>{scenario.difficulty}</span></div><h3>{scenario.title}</h3><p>{scenario.user_objective}</p><div className="chips">{(JSON.parse(scenario.target_units_json) as string[]).slice(0,3).map((target)=><span key={target}>{target}</span>)}</div><Button onClick={()=>start(scenario)}>Start {modes.find(([value])=>value===mode)?.[1].toLowerCase()} <ArrowRight/></Button></Panel>)}</div></div>}

type Turn={id:string;speaker:string;text:string;turn_index:number};type SessionData={session:{id:string;title:string;status:string;mode:string;evaluation_json?:string};turns:Turn[]};type RetryItem={id:number;prompt:string;model:string;variant:string};
export function SpeakSession(){
  const {sessionId}=useParams();const state=useAsync(()=>api<SessionData>(`/api/speaking/sessions/${sessionId}`),[sessionId]);const [text,setText]=useState('');const [sending,setSending]=useState(false);const [recording,setRecording]=useState(false);const [retryItems,setRetryItems]=useState<RetryItem[]>([]);const [revealedRetry,setRevealedRetry]=useState<number[]>([]);const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const pendingCoachAudio=useRef(false);const spokenCoachId=useRef('');
  useEffect(()=>{if(state.data?.session.status!=='processing')return;const timer=setTimeout(()=>void state.reload(),1200);return()=>clearTimeout(timer);},[state.data?.session.status,state.reload]);
  useEffect(()=>{if(!pendingCoachAudio.current)return;const coach=[...(state.data?.turns??[])].reverse().find((turn)=>turn.speaker==='assistant');if(coach&&coach.id!==spokenCoachId.current){spokenCoachId.current=coach.id;pendingCoachAudio.current=false;speakEnglish(coach.text);}},[state.data?.turns]);
  const sendText=()=>{if(!text.trim())return;pendingCoachAudio.current=true;setSending(true);void post(`/api/speaking/sessions/${sessionId}/turns`,{text,durationMs:5000}).then(()=>{setText('');return state.reload();}).finally(()=>setSending(false));};
  const toggleRecord=async()=>{if(recording){recorder.current?.stop();setRecording(false);return;}const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const active=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':undefined});recorder.current=active;active.ondataavailable=(event)=>chunks.current.push(event.data);active.onstop=()=>{stream.getTracks().forEach((track)=>track.stop());const form=new FormData();form.set('audio',new File(chunks.current,'turn.webm',{type:active.mimeType||'audio/webm'}));form.set('durationMs','5000');pendingCoachAudio.current=true;setSending(true);void post(`/api/speaking/sessions/${sessionId}/turns`,form).then(()=>state.reload()).finally(()=>setSending(false));};active.start();setRecording(true);};
  const finish=()=>void post(`/api/speaking/sessions/${sessionId}/finish`).then(()=>state.reload());const buildRetry=()=>void post<{items:RetryItem[]}>(`/api/speaking/sessions/${sessionId}/retry`,{}).then((result)=>setRetryItems(result.items));
  if(!state.data)return <div className="page"/>;const evaluation=state.data.session.evaluation_json?JSON.parse(state.data.session.evaluation_json) as {summary:string;priorityCorrections:Array<{original:string;improved:string;reason:string}>}:null;
  return <div className="page speak-session"><div className="session-head"><div><Eyebrow>{state.data.session.mode} mode</Eyebrow><h1>{state.data.session.title}</h1></div>{!evaluation&&<Button disabled={state.data.session.status==='processing'} className="ghost" onClick={finish}>{state.data.session.status==='processing'?'Analyzing…':'Finish & analyze'}</Button>}</div><Panel className="transcript">{state.data.turns.length===0&&<Empty title="You have the first turn">State your objective, then ask one clear question.</Empty>}{state.data.turns.map((turn)=><div className={`turn ${turn.speaker}`} key={turn.id}><span>{turn.speaker==='user'?'ERIC':'COACH'}</span><p>{turn.text}</p>{turn.speaker==='assistant'&&<SpeechButton text={turn.text} label="Replay coach"/>}</div>)}</Panel>{evaluation?<Panel className="evaluation"><Eyebrow>SESSION REVIEW</Eyebrow><h2>{evaluation.summary}</h2>{evaluation.priorityCorrections.map((correction)=><div className="correction" key={correction.original}><del>{correction.original}</del><strong>{correction.improved}</strong><SpeechButton text={correction.improved} label="Hear correction"/><p>{correction.reason}</p></div>)}<Button onClick={buildRetry}>Build the focused re-say loop <ArrowRight/></Button>{retryItems.length>0&&<div className="retry-list">{retryItems.map((item)=><div className="retry-item" key={item.id}><Eyebrow>RE-SAY {item.id}</Eyebrow><p>{item.prompt}</p><Button className="ghost" onClick={()=>setRevealedRetry((values)=>{if(!values.includes(item.id))speakEnglish(item.model);return values.includes(item.id)?values:[...values,item.id]})}>{revealedRetry.includes(item.id)?item.model:'Reveal & hear model'}</Button>{revealedRetry.includes(item.id)&&<><SpeechButton text={item.model} label="Replay model"/><small>{item.variant}</small></>}</div>)}</div>}</Panel>:state.data.session.status!=='processing'&&<div className="composer"><Button className={`record ${recording?'recording':''}`} onClick={()=>void toggleRecord()}>{recording?<Square/>:<Mic/>}</Button><textarea value={text} onChange={(event)=>setText(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendText();}}} placeholder={recording?'Recording… speak naturally':'Type a turn, or hold the room with your voice…'}/><Button disabled={sending||(!text.trim()&&!recording)} onClick={sendText}>{sending?'…':<Send/>}</Button></div>}</div>;
}
