import { env,exports } from 'cloudflare:workers';
import { describe,expect,it } from 'vitest';
const request=(path:string,init:RequestInit={})=>exports.default.fetch(new Request(`http://app.test${path}`,{...init,headers:{origin:'http://app.test','x-eric-csrf':'1',...(init.body instanceof FormData?{}:{'content-type':'application/json'}),...init.headers}}));
const json=async(path:string,init:RequestInit={})=>{const response=await request(path,init);const payload=await response.json() as Record<string,unknown>;expect(response.status,JSON.stringify(payload)).toBeLessThan(400);return payload;};
describe('connected production paths',()=>{it('bootstraps, persists learning flows, and exports',async()=>{
  const boot=await json('/api/bootstrap',{method:'POST',body:'{}'});expect(boot.units).toBe(240);expect(boot.scenarios).toBe(50);
  const counts=await env.DB.prepare('SELECT (SELECT COUNT(*) FROM learning_units) units,(SELECT COUNT(*) FROM scenarios) scenarios,(SELECT COUNT(*) FROM review_cards) cards').first<{units:number;scenarios:number;cards:number}>();expect(counts).toEqual({units:240,scenarios:50,cards:960});
  const today=await json('/api/today');expect((today.items as unknown[]).length).toBe(6);
  const due=await json('/api/reviews/due?limit=1');const card=(due.cards as Array<{id:string}>)[0];const review=await json(`/api/reviews/${card.id}/answer`,{method:'POST',body:JSON.stringify({response:'concise',correct:true,responseMs:2500,hintLevel:0,rating:4})});expect(review.rating).toBe(4);expect((await env.DB.prepare('SELECT COUNT(*) count FROM review_events').first<{count:number}>())?.count).toBe(1);
  const writing=await json('/api/writing/evaluate',{method:'POST',body:JSON.stringify({taskType:'text_30s',prompt:'Ask about rent',text:'Can the price lower?'})});expect(writing.natural).toBeTruthy();
  const scenarios=await json('/api/speaking/scenarios');const scenario=(scenarios.scenarios as Array<{id:string}>)[0];const session=await json('/api/speaking/sessions',{method:'POST',body:JSON.stringify({scenarioId:scenario.id,mode:'fluency',title:'Test call'})});const sessionId=String(session.id);const turn=await json(`/api/speaking/sessions/${sessionId}/turns`,{method:'POST',body:JSON.stringify({text:'Could you clarify the CAM charges?',durationMs:4000})});expect((turn.assistant as {text:string}).text).toBeTruthy();const ownerHeaders={'cf-access-authenticated-user-email':env.OWNER_EMAIL};const realtimeEvent={eventId:'realtime-user-1',eventType:'user_transcript',text:'Please clarify the rent.',durationMs:1200};await json(`/api/realtime/sessions/${sessionId}/events`,{method:'POST',headers:ownerHeaders,body:JSON.stringify(realtimeEvent)});const duplicate=await json(`/api/realtime/sessions/${sessionId}/events`,{method:'POST',headers:ownerHeaders,body:JSON.stringify(realtimeEvent)});expect(duplicate.deduplicated).toBe(true);expect((await env.DB.prepare('SELECT COUNT(*) count FROM realtime_events WHERE event_id=?').bind(realtimeEvent.eventId).first<{count:number}>())?.count).toBe(1);const beforeBlank=(await env.DB.prepare('SELECT COUNT(*) count FROM practice_turns WHERE session_id=?').bind(sessionId).first<{count:number}>())?.count;await json(`/api/realtime/sessions/${sessionId}/events`,{method:'POST',headers:ownerHeaders,body:JSON.stringify({eventId:'realtime-blank-delta',eventType:'assistant_transcript'})});expect((await env.DB.prepare('SELECT COUNT(*) count FROM practice_turns WHERE session_id=?').bind(sessionId).first<{count:number}>())?.count).toBe(beforeBlank);
  const capture=await json('/api/captures',{method:'POST',body:JSON.stringify({captureType:'missed_phrase',text:'Call me at 212-555-0100. Can the price lower?',context:'listing call',redactAddresses:false})});expect(((capture.redactionPreview as {findings:string[]}).findings)).toContain('PHONE');
  const progress=await json('/api/progress/summary');expect(progress.unitStatusFunnel).toBeTruthy();
  const exported=await json('/api/export',{method:'POST',body:JSON.stringify({format:'json'})});const download=await request(String(exported.downloadUrl));expect(download.status).toBe(200);expect((await download.text())).toContain('exportedAt');
});it('rejects unauthenticated server TTS before provider or cache access',async()=>{const response=await request('/api/audio/tts',{method:'POST',body:JSON.stringify({text:'hello'})});expect(response.status).toBe(401);expect(await response.json()).toEqual({error:'Owner authentication is required.'});});it('completes assessment evidence, audio capture, drills, and after-action review',async()=>{
  await json('/api/bootstrap',{method:'POST',body:'{}'});
  const assessment=await json('/api/assessments',{method:'POST',body:'{}'});const assessmentId=String(assessment.id);const premature=await request(`/api/assessments/${assessmentId}/complete`,{method:'POST',body:'{}'});expect(premature.status).toBe(400);
  const repeated={itemId:'dedupe-item',section:'receptive',responseText:'first',correct:true,responseMs:1000,replayCount:0,hintLevel:0};await json(`/api/assessments/${assessmentId}/responses`,{method:'POST',body:JSON.stringify(repeated)});await json(`/api/assessments/${assessmentId}/responses`,{method:'POST',body:JSON.stringify({...repeated,responseText:'replacement'})});expect((await env.DB.prepare('SELECT COUNT(*) count FROM assessment_responses WHERE assessment_id=? AND item_id=?').bind(assessmentId,'dedupe-item').first<{count:number}>())?.count).toBe(1);await env.DB.prepare('DELETE FROM assessment_responses WHERE assessment_id=? AND item_id=?').bind(assessmentId,'dedupe-item').run();
  const sections=[...Array(60).fill('receptive'),...Array(30).fill('active_recall'),...Array(2).fill('writing'),...Array(3).fill('speaking'),...Array(2).fill('listening')] as string[];await env.DB.batch(sections.map((section,index)=>env.DB.prepare(`INSERT INTO assessment_responses(id,assessment_id,item_id,section,response_text,correct,response_ms,replay_count,hint_level,evaluation_json) VALUES(?,?,?,?,?,1,2000,0,0,'{}')`).bind(`response-${index}`,assessmentId,`item-${index}`,section,'A complete unaided response.')));const completed=await json(`/api/assessments/${assessmentId}/complete`,{method:'POST',body:'{}'});expect((completed.objective as {responses:number}).responses).toBe(97);expect((completed.evaluator as {speaking:number}).speaking).toBe(3);
  const assessmentAudio=new FormData();assessmentAudio.set('audio',new File([new Uint8Array([1,2,3])],'anchor.webm',{type:'audio/webm'}));const transcript=await json(`/api/assessments/${assessmentId}/transcribe`,{method:'POST',body:assessmentAudio});expect(transcript.audioKey).toMatch(/^audio\/assessments\//);
  const captureAudio=new FormData();captureAudio.set('audio',new File([new Uint8Array([1,2,3])],'capture.webm',{type:'audio/webm'}));captureAudio.set('context','test call');const voiceCapture=await json('/api/captures/audio',{method:'POST',body:captureAudio});expect(voiceCapture.transcript).toContain('clarify');
  const manifest=await json('/api/audio/manifest');const audioObjects=manifest.objects as Array<{downloadUrl:string}>;expect(audioObjects.length).toBe(2);const audioDownload=await request(audioObjects[0].downloadUrl);expect(audioDownload.status).toBe(200);expect(audioDownload.headers.get('content-disposition')).toContain('attachment');
  const unit=(await env.DB.prepare('SELECT id FROM learning_units ORDER BY id LIMIT 1').first<{id:string}>())!;const drill=await json('/api/drills/sessions',{method:'POST',body:'{}'});await json(`/api/drills/sessions/${String(drill.id)}/answers`,{method:'POST',body:JSON.stringify({unitId:unit.id,prompt:'Use it now',response:'A spoken answer',correct:true,responseMs:1800,variant:1})});await json(`/api/drills/sessions/${String(drill.id)}/complete`,{method:'POST',body:'{}'});expect((await env.DB.prepare(`SELECT status FROM practice_sessions WHERE id=?`).bind(drill.id).first<{status:string}>())?.status).toBe('complete');
  const prepared=await json('/api/event-prep',{method:'POST',body:JSON.stringify({event:'Call the listing agent tomorrow.'})});const after=await json(`/api/event-prep/${String(prepared.id)}/after-action`,{method:'POST',body:JSON.stringify({happened:'We confirmed the next tour.',missedPhrase:'Ask about flexibility.',unfamiliarExpression:'tenant improvement allowance',createFollowUp:true})});expect(after.followUp).toBeTruthy();
});});
