import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createEmptyCard } from 'ts-fsrs';

const remote=process.argv.includes('--remote');
const units=readFileSync('seed/core-units.jsonl','utf8').trim().split('\n').map((line)=>JSON.parse(line) as Record<string,unknown>);
const scenarios=readFileSync('seed/scenarios.jsonl','utf8').trim().split('\n').map((line)=>JSON.parse(line) as Record<string,unknown>);
const baseline=JSON.parse(readFileSync('seed/personal-baseline.json','utf8')) as Record<string,unknown>;
const s=(value:unknown)=>value===null||value===undefined?'NULL':`'${String(value).replaceAll("'","''")}'`;
const j=(value:unknown)=>s(JSON.stringify(value));
const sql:string[]=['PRAGMA foreign_keys = ON;',`INSERT OR IGNORE INTO users(id,display_name,timezone) VALUES('primary',${s(baseline.displayName)},${s(baseline.timezone)});`,`INSERT OR IGNORE INTO learner_profiles(user_id,working_cefr,target_cefr,support_language,daily_minutes,weekly_days,goals_json,strengths_json,weaknesses_json,scaffolding_level) VALUES('primary',${s(baseline.workingLevel)},${s(baseline.target)},${s(baseline.supportLanguage)},${Number(baseline.dailyMinutes)},${Number(baseline.weeklyDays)},${j(baseline.priorityContexts)},${j(baseline.strengths)},${j(baseline.weaknesses)},2);`];
for(const u of units){sql.push(`INSERT INTO learning_units(id,unit_type,term,normalized_term,lemma,part_of_speech,ipa,cefr,priority,register,domains_json,definition_en,definition_zh,collocations_json,examples_json,confusions_json,source,content_version,active) VALUES(${s(u.id)},${s(u.unitType)},${s(u.term)},${s(u.normalizedTerm)},${s(u.lemma)},${s(u.partOfSpeech)},${s(u.ipa)},${s(u.cefr)},${Number(u.priority)},${s(u.register)},${j(u.domains)},${s(u.definitionEn)},${s(u.definitionZh)},${j(u.collocations)},${j(u.examples)},${j(u.confusions)},'seed',${Number(u.contentVersion)},1) ON CONFLICT(id) DO UPDATE SET unit_type=excluded.unit_type,term=excluded.term,normalized_term=excluded.normalized_term,lemma=excluded.lemma,part_of_speech=excluded.part_of_speech,ipa=excluded.ipa,cefr=excluded.cefr,priority=excluded.priority,register=excluded.register,domains_json=excluded.domains_json,definition_en=excluded.definition_en,definition_zh=excluded.definition_zh,collocations_json=excluded.collocations_json,examples_json=excluded.examples_json,confusions_json=excluded.confusions_json,source=excluded.source,content_version=excluded.content_version,active=excluded.active;`,`INSERT OR IGNORE INTO user_unit_states(user_id,unit_id) VALUES('primary',${s(u.id)});`);for(const type of ['recognition','active_recall','cloze','listening_recall']){const card=createEmptyCard(new Date());sql.push(`INSERT OR IGNORE INTO review_cards(id,user_id,unit_id,card_type,state,due_at,stability,difficulty,elapsed_days,scheduled_days,learning_steps,reps,lapses,last_review_at,fsrs_json) VALUES(${s(`card-${String(u.id)}-${type}`)},'primary',${s(u.id)},${s(type)},${card.state},${s(card.due.toISOString())},${card.stability},${card.difficulty},${card.elapsed_days},${card.scheduled_days},${card.learning_steps},${card.reps},${card.lapses},NULL,${j(card)});`);}}
for(const x of scenarios)sql.push(`INSERT INTO scenarios(id,title,domain,difficulty,ai_role,user_objective,target_units_json,hidden_complication,max_turns,rubric_json,completion_condition,source,active) VALUES(${s(x.id)},${s(x.title)},${s(x.domain)},${s(x.difficulty)},${s(x.aiRole)},${s(x.userObjective)},${j(x.targetUnits)},${s(x.hiddenComplication)},${Number(x.maxTurns)},${j(x.rubric)},${s(x.completionCondition)},'seed',1) ON CONFLICT(id) DO UPDATE SET title=excluded.title,domain=excluded.domain,difficulty=excluded.difficulty,ai_role=excluded.ai_role,user_objective=excluded.user_objective,target_units_json=excluded.target_units_json,hidden_complication=excluded.hidden_complication,max_turns=excluded.max_turns,rubric_json=excluded.rubric_json,completion_condition=excluded.completion_condition,source=excluded.source,active=excluded.active;`);
sql.push("INSERT OR IGNORE INTO app_settings(key,value_json) VALUES('budget','{\"dailyAiCallLimit\":60,\"dailyAudioMinuteSoftLimit\":30,\"monthlyEstimatedCostAlert\":25,\"strongModelCallsPerDay\":6}');");
const dir=mkdtempSync(join(tmpdir(),'english-os-seed-'));const file=join(dir,'seed.sql');writeFileSync(file,sql.join('\n'));
try{const result=spawnSync('pnpm',['exec','wrangler','d1','execute',process.env.D1_NAME||'eric-english-os-db',remote?'--remote':'--local','--file',file],{encoding:'utf8'});if(result.status!==0){process.stderr.write(`${result.stdout}${result.stderr}`);process.exit(result.status??1);}console.log(JSON.stringify({mode:remote?'remote':'local',units:units.length,scenarios:scenarios.length,cards:units.length*4}));}finally{rmSync(dir,{recursive:true,force:true});}
