interface Env {
  AI_GATEWAY_TOKEN?: string;
  AI_GATEWAY_BYOK_ALIAS?: string;
  DIRECT_LLM_API_KEY?: string;
  DIRECT_STT_API_KEY?: string;
  DIRECT_TTS_API_KEY?: string;
  OWNER_EMAIL?: string;
  AZURE_OPENAI_API_KEY?: string;
  AZURE_SPEECH_KEY?: string;
  AZURE_OPENAI_ENDPOINT?: string;
  AZURE_REALTIME_DEPLOYMENT?: string;
  AZURE_TTS_DEPLOYMENT?: string;
  AZURE_TRANSCRIBE_DEPLOYMENT?: string;
  AZURE_TEXT_DEPLOYMENT?: string;
  REALTIME_SPEAK_ENABLED?: string;
  PRONUNCIATION_ASSESSMENT_ENABLED?: string;
  SPEECH_MODE?: string;
  AZURE_OPENAI_API_VERSION?: string;
  AZURE_TTS_VOICE?: string;
  AZURE_TTS_FORMAT?: string;
}
