import { BrowserFallbackTtsProvider, MockSttProvider, MockTextProvider } from './mock';
import { OpenAiCompatibleSttProvider, OpenAiCompatibleTextProvider, OpenAiCompatibleTtsProvider } from './openai-compatible';
import type { ProviderBundle, SpeechToTextProvider, TranscriptResult } from './types';
import type { AiUsageEvent } from './openai-compatible';
import { json } from '../../worker/services/db';
import { WorkersAiTextProvider } from './workers-ai';

class WorkersAiSttProvider implements SpeechToTextProvider {
  constructor(private readonly ai:Ai,private readonly model:string,private readonly gatewayId:string,private readonly beforeRequest?:(input:{taskType:string})=>Promise<void>,private readonly usageSink?:(event:AiUsageEvent)=>Promise<void>){}
  async transcribe(audio:ArrayBuffer,_mimeType:string):Promise<TranscriptResult>{const started=Date.now();await this.beforeRequest?.({taskType:'transcription'});try{const bytes=[...new Uint8Array(audio)];const result=await this.ai.run(this.model as Parameters<Ai['run']>[0],{audio:bytes} as never,{gateway:{id:this.gatewayId,skipCache:true,collectLog:false,retries:{maxAttempts:2,backoff:'exponential'}}}) as {text?:string};if(typeof result.text!=='string')throw new Error('Workers AI returned no transcript');await this.usageSink?.({taskType:'transcription',provider:'workers-ai',model:this.model,latencyMs:Date.now()-started,estimatedCost:0,success:true});return{text:result.text,provider:'workers-ai',model:this.model};}catch(error){await this.usageSink?.({taskType:'transcription',provider:'workers-ai',model:this.model,latencyMs:Date.now()-started,estimatedCost:0,success:false,errorCode:error instanceof Error?error.name:'unknown'});throw error;}}
}

export function createProviders(env:Env):ProviderBundle {
  const mode=String(env.AI_PROVIDER_MODE || 'mock');
  if(mode==='mock')return{text:new MockTextProvider(),stt:new MockSttProvider(),tts:new BrowserFallbackTtsProvider(),mode};
  const gatewayBase=(env.AI_GATEWAY_API_BASE || `https://gateway.ai.cloudflare.com/v1/${env.AI_GATEWAY_ACCOUNT_ID || ''}/${env.AI_GATEWAY_ID}/openai`).replace(/\/$/,'');
  const directBase=env.DIRECT_LLM_API_BASE || 'https://api.openai.com/v1'; const gateway=mode==='cloudflare_gateway'||mode==='workers_ai_stt';
  const beforeRequest=async(input:{taskType:string;modelRole?:'daily_fast'|'evaluator_strong'|'content_generator'})=>{const row=await env.DB.prepare(`SELECT value_json FROM app_settings WHERE key='budget'`).first<{value_json:string}>();const budget=json(row?.value_json,{dailyAiCallLimit:60,strongModelCallsPerDay:6,monthlyEstimatedCostAlert:Number(env.MONTHLY_AI_BUDGET_USD||25)});const daily=await env.DB.prepare(`SELECT COUNT(*) count FROM ai_usage_events WHERE created_at>=datetime('now','start of day')`).first<{count:number}>();if((daily?.count??0)>=budget.dailyAiCallLimit)throw new Error('Daily AI call limit reached. Reviews and deterministic plans remain available.');if(input.modelRole==='evaluator_strong'){const strong=await env.DB.prepare(`SELECT COUNT(*) count FROM ai_usage_events WHERE model=? AND created_at>=datetime('now','start of day')`).bind(env.AI_MODEL_STRONG).first<{count:number}>();if((strong?.count??0)>=budget.strongModelCallsPerDay)throw new Error('Daily strong-model limit reached.');}const month=await env.DB.prepare(`SELECT COALESCE(SUM(estimated_cost),0) total FROM ai_usage_events WHERE created_at>=datetime('now','start of month')`).first<{total:number}>();const monthlyLimit=Math.min(Number(env.MONTHLY_AI_BUDGET_USD||budget.monthlyEstimatedCostAlert),budget.monthlyEstimatedCostAlert);if((month?.total??0)>=monthlyLimit)throw new Error('Monthly AI budget alert threshold reached.');};
  const usageSink=async(event:AiUsageEvent)=>{try{await env.DB.prepare(`INSERT INTO ai_usage_events(id,task_type,provider,model,latency_ms,input_tokens,output_tokens,audio_seconds,estimated_cost,success,error_code) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),event.taskType,event.provider,event.model,event.latencyMs,event.inputTokens??null,event.outputTokens??null,event.audioSeconds??null,event.estimatedCost,event.success?1:0,event.errorCode??null).run();}catch{/* Telemetry must never replace the primary provider result. */}};
  if(mode==='workers_ai')return{text:new WorkersAiTextProvider({ai:env.AI,gatewayId:env.AI_GATEWAY_ID,models:{daily_fast:env.AI_MODEL_FAST,evaluator_strong:env.AI_MODEL_STRONG,content_generator:env.AI_MODEL_CONTENT},beforeRequest,usageSink}),stt:new WorkersAiSttProvider(env.AI,env.AI_MODEL_STT,env.AI_GATEWAY_ID,beforeRequest,usageSink),tts:new BrowserFallbackTtsProvider(),mode};
  const options={baseUrl:gateway?gatewayBase:directBase,apiKey:gateway?undefined:env.DIRECT_LLM_API_KEY,gatewayToken:gateway?env.AI_GATEWAY_TOKEN:undefined,byokAlias:gateway?env.AI_GATEWAY_BYOK_ALIAS:undefined,models:{daily_fast:env.AI_MODEL_FAST,evaluator_strong:env.AI_MODEL_STRONG,content_generator:env.AI_MODEL_CONTENT},providerName:gateway?'cloudflare-ai-gateway':'openai-compatible',beforeRequest,usageSink};
  const sttOptions={...options,apiKey:gateway?undefined:env.DIRECT_STT_API_KEY||env.DIRECT_LLM_API_KEY};const ttsOptions={...options,apiKey:gateway?undefined:env.DIRECT_TTS_API_KEY||env.DIRECT_LLM_API_KEY};
  return{text:new OpenAiCompatibleTextProvider(options),stt:mode==='workers_ai_stt'?new WorkersAiSttProvider(env.AI,env.AI_MODEL_STT,env.AI_GATEWAY_ID,beforeRequest,usageSink):new OpenAiCompatibleSttProvider(sttOptions,env.AI_MODEL_STT),tts:env.AI_MODEL_TTS?new OpenAiCompatibleTtsProvider(ttsOptions,env.AI_MODEL_TTS):new BrowserFallbackTtsProvider(),mode};
}
